//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMI
{
    using System;
    
    public partial class Sp_AllPedido_Result1
    {
        public int Id { get; set; }
        public string Folio { get; set; }
        public string Categoria { get; set; }
        public string Descripcion { get; set; }
        public string Unidad { get; set; }
        public int Cantidad { get; set; }
        public int Autoriza { get; set; }
        public int Estatus { get; set; }
        public int Surtido { get; set; }
        public string Formato { get; set; }
        public string NombreFormato { get; set; }
        public string Usuario { get; set; }
        public string Area { get; set; }
        public System.DateTime Fecha { get; set; }
    }
}
