//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMI
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TbOportunidad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TbOportunidad()
        {
            this.TbAreaInteres = new HashSet<TbAreaInteres>();
            this.TbTipoOportunidad = new HashSet<TbTipoOportunidad>();
        }
    
        public int Id { get; set; }
        public string Folio { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        [RegularExpression("(0[1-9]|[12][0-9]|3[01])[- /.](0[1-9]|1[012])[- /.](19|20)\\d\\d", ErrorMessage = "Fecha Invalida")]

        public System.DateTime Fecha { get; set; }
        public string Fecha2 {
            get
            {
            return String.Format("{0:dd/MM/yyyy}", Fecha);//String.Format("{0:yyy/MM/dd}", Fecha);
            }
        }
        public System.DateTime FechaSistema { get; set; }
        public string Representante { get; set; }
        public string Telefono { get; set; }
        public string Correo { get; set; }
        public int MedioContacto { get; set; }
        public string Descripcion { get; set; }
        public int idFormato { get; set; }
        public int idUsuario { get; set; }
        public string Compania { get; set; }
    
        public virtual TbFormato TbFormato { get; set; }
        public virtual TbMedioContacto TbMedioContacto { get; set; }
        public virtual TbUsuario TbUsuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TbAreaInteres> TbAreaInteres { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TbTipoOportunidad> TbTipoOportunidad { get; set; }


    }
}
