//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMI
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbPedidoPersonal
    {
        public int Id { get; set; }
        public Nullable<int> IdTipoEspecialidad { get; set; }
        public Nullable<int> IdProfesion { get; set; }
        public Nullable<int> IdCategoriaRH { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<int> Supervisor { get; set; }
        public Nullable<int> Estatus { get; set; }
        public int IdSolicitud { get; set; }
        public Nullable<int> Dato { get; set; }
    
        public virtual TbCategoriaRH TbCategoriaRH { get; set; }
        public virtual TbEspecialidad TbEspecialidad { get; set; }
        public virtual TbProfesion TbProfesion { get; set; }
        public virtual TbStatusAutorizacion TbStatusAutorizacion { get; set; }
        public virtual TbUsuario TbUsuario { get; set; }
        public virtual TbSolicitud TbSolicitud { get; set; }
    }
}
