//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMI
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbSolicitud
    {
        public int IdSolicitud { get; set; }
        public Nullable<int> IdFormato { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public Nullable<int> TipoMaterialPersonal { get; set; }
        public Nullable<int> IdPedidoP { get; set; }
        public Nullable<int> IdPedidoM { get; set; }
    
        public virtual TbFormato TbFormato { get; set; }
        public virtual TbPedidoPersonal TbPedidoPersonal { get; set; }
        public virtual TbUsuario TbUsuario { get; set; }
        public virtual TbPedidoM TbPedidoM { get; set; }
    }
}
