//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OIM_DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class OIMEntity : DbContext
    {
        public OIMEntity()
            : base("name=OIMEntity")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Supervisores> Supervisores { get; set; }
        public virtual DbSet<TablaDirectorio> TablaDirectorio { get; set; }
        public virtual DbSet<TablaMaestra> TablaMaestra { get; set; }
        public virtual DbSet<TbArea> TbArea { get; set; }
        public virtual DbSet<TbAreaInteres> TbAreaInteres { get; set; }
        public virtual DbSet<TbCategoria> TbCategoria { get; set; }
        public virtual DbSet<TbCategoriaRH> TbCategoriaRH { get; set; }
        public virtual DbSet<TbCompras> TbCompras { get; set; }
        public virtual DbSet<TbEspecialidad> TbEspecialidad { get; set; }
        public virtual DbSet<TbFormato> TbFormato { get; set; }
        public virtual DbSet<TbMedioContacto> TbMedioContacto { get; set; }
        public virtual DbSet<TbOportunidad> TbOportunidad { get; set; }
        public virtual DbSet<TbOrdenCompra> TbOrdenCompra { get; set; }
        public virtual DbSet<TbPedidoM> TbPedidoM { get; set; }
        public virtual DbSet<TbPedidoPersonal> TbPedidoPersonal { get; set; }
        public virtual DbSet<TbProfesion> TbProfesion { get; set; }
        public virtual DbSet<TbProveedores> TbProveedores { get; set; }
        public virtual DbSet<TbSolicitud> TbSolicitud { get; set; }
        public virtual DbSet<TbStatusAutorizacion> TbStatusAutorizacion { get; set; }
        public virtual DbSet<TbTipoOportunidad> TbTipoOportunidad { get; set; }
        public virtual DbSet<TbUnidad> TbUnidad { get; set; }
        public virtual DbSet<TbUnidadNegocios> TbUnidadNegocios { get; set; }
        public virtual DbSet<TbUnidadTecnica> TbUnidadTecnica { get; set; }
        public virtual DbSet<TbUsuario> TbUsuario { get; set; }
        public virtual DbSet<TbInve_Equipo_Comp> TbInve_Equipo_Comp { get; set; }
        public virtual DbSet<Tb_EstadoEquipo> Tb_EstadoEquipo { get; set; }
        public virtual DbSet<TbInve_Equipo_Varios> TbInve_Equipo_Varios { get; set; }
        public virtual DbSet<Tb_EstadoLic> Tb_EstadoLic { get; set; }
        public virtual DbSet<TbInve_Licencias> TbInve_Licencias { get; set; }
        public virtual DbSet<TbInve_Papeleria> TbInve_Papeleria { get; set; }
        public virtual DbSet<Tb_EstadoVehiculo> Tb_EstadoVehiculo { get; set; }
        public virtual DbSet<TbInve_Vehiculos> TbInve_Vehiculos { get; set; }
        public virtual DbSet<Tb_Estado_OnOff> Tb_Estado_OnOff { get; set; }
        public virtual DbSet<TbSolicitudCotizacion> TbSolicitudCotizacion { get; set; }
    
        public virtual ObjectResult<Sp_AllPedido_Result> Sp_AllPedido()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_AllPedido_Result>("Sp_AllPedido");
        }
    
        public virtual ObjectResult<Nullable<decimal>> Sp_Suma(Nullable<int> orden)
        {
            var ordenParameter = orden.HasValue ?
                new ObjectParameter("Orden", orden) :
                new ObjectParameter("Orden", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("Sp_Suma", ordenParameter);
        }
    
        public virtual ObjectResult<Sp_AllPedidoXEstatusXAdmin_Result> Sp_AllPedidoXEstatusXAdmin(Nullable<int> estatus, Nullable<int> orden)
        {
            var estatusParameter = estatus.HasValue ?
                new ObjectParameter("Estatus", estatus) :
                new ObjectParameter("Estatus", typeof(int));
    
            var ordenParameter = orden.HasValue ?
                new ObjectParameter("Orden", orden) :
                new ObjectParameter("Orden", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_AllPedidoXEstatusXAdmin_Result>("Sp_AllPedidoXEstatusXAdmin", estatusParameter, ordenParameter);
        }
    
        public virtual int Sp_Total(Nullable<int> id, Nullable<decimal> valor)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var valorParameter = valor.HasValue ?
                new ObjectParameter("Valor", valor) :
                new ObjectParameter("Valor", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Total", idParameter, valorParameter);
        }
    
        public virtual ObjectResult<Sp_Historial_Result> Sp_Historial()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_Historial_Result>("Sp_Historial");
        }
    
        public virtual ObjectResult<Sp_AllPedidoXEstatus_Result> Sp_AllPedidoXEstatus(Nullable<int> estatus)
        {
            var estatusParameter = estatus.HasValue ?
                new ObjectParameter("Estatus", estatus) :
                new ObjectParameter("Estatus", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_AllPedidoXEstatus_Result>("Sp_AllPedidoXEstatus", estatusParameter);
        }
    }
}
