//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OIM_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbCompras
    {
        public int Id { get; set; }
        public string Folio { get; set; }
        public string NombreProveedor { get; set; }
        public Nullable<int> ClaveProveedor { get; set; }
        public Nullable<System.DateTime> FechaOrden { get; set; }
        public Nullable<bool> Open { get; set; }
        public Nullable<int> IdFormato { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public Nullable<int> IdProveedor { get; set; }
    
        public virtual TbFormato TbFormato { get; set; }
        public virtual TbUsuario TbUsuario { get; set; }
        public virtual TbProveedores TbProveedores { get; set; }
    }
}
