//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OIM_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbInve_Papeleria
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> FechaEntrega { get; set; }
        public string FolioEntrega { get; set; }
    
        public virtual TbPedidoM TbPedidoM { get; set; }
    }
}
