//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OIM_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbInve_Equipo_Varios
    {
        public int Id { get; set; }
        public string Tipo { get; set; }
        public string Nombre { get; set; }
        public string Serie { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public Nullable<int> Estado { get; set; }
        public string Modelo { get; set; }
    
        public virtual Tb_EstadoEquipo Tb_EstadoEquipo { get; set; }
    }
}
