//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OIM_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbPedidoM
    {
        public int Id { get; set; }
        public int IdCategoria { get; set; }
        public string Descripcion { get; set; }
        public int IdUnidad { get; set; }
        public int Cantidad { get; set; }
        public int IdSupervisor { get; set; }
        public int Estatus { get; set; }
        public int Surtido { get; set; }
        public int Dato { get; set; }
        public Nullable<System.DateTime> FechaAutorizacion { get; set; }
        public string Proveedor { get; set; }
        public Nullable<int> Autorizacion { get; set; }
        public string Observacion { get; set; }
        public Nullable<int> OrdenCompra { get; set; }
        public int  IdSolicitud { get; set; }
        public Nullable<int> IdOrdenCompra { get; set; }
        public Nullable<int> IdProveedor { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<decimal> Importe { get; set; }
    
        public virtual Supervisores Supervisores { get; set; }
        public virtual TbCategoria TbCategoria { get; set; }
        public virtual TbCompras TbCompras { get; set; }
        public virtual TbOrdenCompra TbOrdenCompra { get; set; }
        public virtual TbSolicitud TbSolicitud { get; set; }
        public virtual TbUnidad TbUnidad { get; set; }
        public virtual TbStatusAutorizacion TbStatusAutorizacion { get; set; }
        public virtual TbProveedores TbProveedores { get; set; }
    }
}
