//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OIM_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbSolicitud
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TbSolicitud()
        {
            this.TbPedidoM = new HashSet<TbPedidoM>();
            this.TbPedidoPersonal = new HashSet<TbPedidoPersonal>();
        }
    
        public int IdSolicitud { get; set; }
        public int IdFormato { get; set; }
        public System.DateTime Fecha { get; set; }
        public int IdUsuario { get; set; }
        public Nullable<int> TipoMaterialPersonal { get; set; }
        public string Folio { get; set; }
        public int EnviadoInfra { get; set; }
        public Nullable<int> EnviadoCom { get; set; }
    
        public virtual TbFormato TbFormato { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TbPedidoM> TbPedidoM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TbPedidoPersonal> TbPedidoPersonal { get; set; }
        public virtual TbUsuario TbUsuario { get; set; }
    }
}
